language: python
python:
  - 2.6
  - 2.7
env:
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.5c2
install:
  - pip install -e git+git://github.com/django/django.git@${DJANGO_VERSION}#egg=django
  - pip install -r requirements.txt --use-mirrors
script: fab test
